spring.messages.encoding=UTF-8
server.port=${PORT:8080}
server.forward-headers-strategy=framework
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.datasource.url=jdbc:mysql://localhost:3306/shopquanao?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia%2FHo_Chi_Minh&createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=javanangcao
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-swallow-size=500MB

# ==================== GOOGLE OAUTH2 ====================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ==================== SEPAY WEBHOOK ====================
sepay.webhook.api-key=${SEPAY_WEBHOOK_API_KEY:kidshopPHONGKHANHLONGJAVANANGCAO}

# ==================== CLOUDFLARE R2 STORAGE ====================
cloudflare.r2.endpoint=https://7e90c8ff8624fc66428f36d94a71ed3a.r2.cloudflarestorage.com
cloudflare.r2.region=auto
cloudflare.r2.bucket=gtaviet
cloudflare.r2.public-base-url=https://pub-8c629d3164234cff8bff2adc237cc48a.r2.dev
cloudflare.r2.object-prefix=
cloudflare.r2.access-key-id=${CLOUDFLARE_R2_ACCESS_KEY_ID:677d19605339b280996bf1be09ef62fb}
cloudflare.r2.secret-access-key=${CLOUDFLARE_R2_SECRET_ACCESS_KEY:68fd2bf38d9efeda8d6a6fa53c1e57c4ec824bb52c1236cb2b9e58f099036340}